"""add_sync_id_to_tracks_and_parsed_tracks_cache

Revision ID: 4a0a9825ea5c
Revises: 774dea0fae22
Create Date: 2026-03-27 12:24:52.574627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0a9825ea5c'
down_revision: Union[str, Sequence[str], None] = '774dea0fae22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the new parsed_tracks cache table (drop legacy raw-SQL version first if it exists)
    op.execute("DROP TABLE IF EXISTS parsed_tracks")
    op.create_table('parsed_tracks',
    sa.Column('raw_string', sa.String(), nullable=False),
    sa.Column('parsed_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('raw_string')
    )

    # Step 1: add sync_id as nullable so existing rows don't violate the constraint
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_id', sa.String(), nullable=True))

    # Step 2: back-fill existing rows with a stable placeholder; the app will
    # recompute correct sync_ids on the next library import.
    op.execute(
        "UPDATE tracks SET sync_id = 'ss:track:legacy:' || CAST(id AS TEXT) "
        "WHERE sync_id IS NULL"
    )

    # Step 3: enforce NOT NULL + unique index via a table rebuild (batch mode)
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('sync_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_tracks_sync_id'), ['sync_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_sync_id'))
        batch_op.drop_column('sync_id')

    op.drop_table('parsed_tracks')
    # ### end Alembic commands ###
