"""drop_acoustid_id_from_tracks

Revision ID: 774dea0fae22
Revises: 
Create Date: 2026-03-27 11:58:49.181139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774dea0fae22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Guard every CREATE/DROP so this migration is idempotent when applied to
    # databases that were initialised with create_all() before Alembic existed.

    # --- tables introduced after initial rollout ---
    conn = op.get_bind()

    existing = {row[0] for row in conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table'"))}

    if 'track_audio_features' not in existing:
        op.create_table('track_audio_features',
        sa.Column('sync_id', sa.String(), nullable=False),
        sa.Column('tempo', sa.Float(), nullable=True),
        sa.Column('energy', sa.Float(), nullable=True),
        sa.Column('valence', sa.Float(), nullable=True),
        sa.Column('danceability', sa.Float(), nullable=True),
        sa.Column('acousticness', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('sync_id')
        )

    if 'artist_aliases' not in existing:
        op.create_table('artist_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('alias', sa.String(), nullable=False),
        sa.Column('locale', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('artist_id', 'alias', name='uq_artist_alias')
        )
        with op.batch_alter_table('artist_aliases', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_artist_aliases_artist_id'), ['artist_id'], unique=False)

    if 'track_aliases' not in existing:
        op.create_table('track_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('track_id', sa.Integer(), nullable=False),
        sa.Column('alias', sa.String(), nullable=False),
        sa.Column('locale', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('track_id', 'alias', name='uq_track_alias')
        )
        with op.batch_alter_table('track_aliases', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_track_aliases_track_id'), ['track_id'], unique=False)

    # --- legacy tables to drop ---
    if 'user_album_ratings' in existing:
        with op.batch_alter_table('user_album_ratings', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_album_ratings_album_id'))
            batch_op.drop_index(batch_op.f('ix_user_album_ratings_user_id'))
        op.drop_table('user_album_ratings')

    if 'user_track_states' in existing:
        with op.batch_alter_table('user_track_states', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_track_states_track_id'))
            batch_op.drop_index(batch_op.f('ix_user_track_states_user_id'))
        op.drop_table('user_track_states')

    if 'user_artist_ratings' in existing:
        with op.batch_alter_table('user_artist_ratings', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_artist_ratings_artist_id'))
            batch_op.drop_index(batch_op.f('ix_user_artist_ratings_user_id'))
        op.drop_table('user_artist_ratings')

    # --- column changes on tracks ---
    track_cols = {row[1] for row in conn.execute(sa.text("PRAGMA table_info('tracks')"))}

    if 'acoustid_id' in track_cols or True:  # always run batch rebuild for isrc type fix
        with op.batch_alter_table('tracks', schema=None) as batch_op:
            batch_op.alter_column('isrc',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
            if 'acoustid_id' in track_cols:
                batch_op.drop_column('acoustid_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acoustid_id', sa.TEXT(), nullable=True))
        batch_op.alter_column('isrc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('user_artist_ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('is_tracked', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist_id', 'source', name=op.f('uq_user_artist_source'))
    )
    with op.batch_alter_table('user_artist_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_artist_ratings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_artist_ratings_artist_id'), ['artist_id'], unique=False)

    op.create_table('user_track_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('is_unlinked', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name=op.f('uq_user_track_state'))
    )
    with op.batch_alter_table('user_track_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_track_states_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_track_states_track_id'), ['track_id'], unique=False)

    op.create_table('user_album_ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'album_id', 'source', name=op.f('uq_user_album_source'))
    )
    with op.batch_alter_table('user_album_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_album_ratings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_album_ratings_album_id'), ['album_id'], unique=False)

    with op.batch_alter_table('track_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_aliases_track_id'))

    op.drop_table('track_aliases')
    with op.batch_alter_table('artist_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_aliases_artist_id'))

    op.drop_table('artist_aliases')
    op.drop_table('track_audio_features')
    # ### end Alembic commands ###
