"""make sync_id unique

Revision ID: 47fc0220d0f9
Revises: b5f9e8a7c1d2
Create Date: 2026-08-05 21:58:07.837510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '47fc0220d0f9'
down_revision: Union[str, None] = 'b5f9e8a7c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks') as batch_op:
        batch_op.create_unique_constraint('uq_tracks_sync_id', ['sync_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks') as batch_op:
        batch_op.drop_constraint('uq_tracks_sync_id', type_='unique')
    # ### end Alembic commands ###
