"""Add sync_id to tracks

Revision ID: aac3c628374f
Revises: 8c8b8d8e8f8a
Create Date: 2026-06-07 15:17:40.852447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac3c628374f'
down_revision: Union[str, None] = '8c8b8d8e8f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identifiers_plugin_source'), ['plugin_source'], unique=False)
        batch_op.create_unique_constraint('uq_plugin_item', ['plugin_source', 'plugin_item_id'])

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_sync_id'), ['sync_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_sync_id'))
        batch_op.drop_column('sync_id')

    with op.batch_alter_table('external_identifiers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plugin_item', type_='unique')
        batch_op.drop_index(batch_op.f('ix_external_identifiers_plugin_source'))

    # ### end Alembic commands ###
