"""Initial schema

Revision ID: cb4f02f432ea
Revises:
Create Date: 2026-03-28 02:05:39.882499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import time_utils


# revision identifiers, used by Alembic.
revision: str = 'cb4f02f432ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_name', sa.String(), nullable=True),
    sa.Column('musicbrainz_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('metadata_status', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_musicbrainz_id'), ['musicbrainz_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_artists_name'), ['name'], unique=False)

    op.create_table('track_audio_features',
    sa.Column('sync_id', sa.String(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('release_group_id', sa.String(), nullable=True),
    sa.Column('mb_release_id', sa.String(), nullable=True),
    sa.Column('original_release_date', sa.Date(), nullable=True),
    sa.Column('album_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_title'), ['title'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sort_title', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('added_at', time_utils.UTCDateTime(), nullable=True),
    sa.Column('musicbrainz_id', sa.String(), nullable=True),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.Column('acoustid_id', sa.String(), nullable=True),
    sa.Column('global_rating', sa.Float(), nullable=True),
    sa.Column('metadata_status', sa.JSON(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_musicbrainz_id'), ['musicbrainz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_title'), ['title'], unique=False)

    op.create_table('audio_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.Column('acoustid_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_hash')
    )
    with op.batch_alter_table('audio_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_fingerprints_track_id'), ['track_id'], unique=False)

    op.create_table('external_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('provider_source', sa.String(), nullable=False),
    sa.Column('provider_item_id', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_source', 'provider_item_id', name='uq_provider_item')
    )
    with op.batch_alter_table('external_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identifiers_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_identifiers_track_id'))

    op.drop_table('external_identifiers')
    with op.batch_alter_table('audio_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_fingerprints_track_id'))

    op.drop_table('audio_fingerprints')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_title'))
        batch_op.drop_index(batch_op.f('ix_tracks_musicbrainz_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_title'))

    op.drop_table('albums')
    op.drop_table('track_audio_features')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_name'))
        batch_op.drop_index(batch_op.f('ix_artists_musicbrainz_id'))

    op.drop_table('artists')
    # ### end Alembic commands ###
