"""add_normalized_hash_columns

Revision ID: eaf4b5d2df68
Revises: aac3c628374f
Create Date: 2026-06-17 07:06:44.430302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eaf4b5d2df68"
down_revision: str | None = "aac3c628374f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    album_cols = []
    album_indexes = []
    if inspector.has_table("albums"):
        album_cols = [c["name"] for c in inspector.get_columns("albums")]
        album_indexes = [idx["name"] for idx in inspector.get_indexes("albums")]

    with op.batch_alter_table("albums", schema=None) as batch_op:
        if "normalized_title" not in album_cols:
            batch_op.add_column(sa.Column("normalized_title", sa.String(), nullable=False, server_default=""))
        if "ix_albums_normalized_title" not in album_indexes:
            batch_op.create_index(batch_op.f("ix_albums_normalized_title"), ["normalized_title"], unique=False)

    artist_cols = []
    artist_indexes = []
    if inspector.has_table("artists"):
        artist_cols = [c["name"] for c in inspector.get_columns("artists")]
        artist_indexes = [idx["name"] for idx in inspector.get_indexes("artists")]

    with op.batch_alter_table("artists", schema=None) as batch_op:
        if "normalized_name" not in artist_cols:
            batch_op.add_column(sa.Column("normalized_name", sa.String(), nullable=False, server_default=""))
        if "ix_artists_normalized_name" not in artist_indexes:
            batch_op.create_index(batch_op.f("ix_artists_normalized_name"), ["normalized_name"], unique=False)

    track_cols = []
    track_indexes = []
    if inspector.has_table("tracks"):
        track_cols = [c["name"] for c in inspector.get_columns("tracks")]
        track_indexes = [idx["name"] for idx in inspector.get_indexes("tracks")]

    with op.batch_alter_table("tracks", schema=None) as batch_op:
        if "normalized_title" not in track_cols:
            batch_op.add_column(sa.Column("normalized_title", sa.String(), nullable=False, server_default=""))
        if "inode" not in track_cols:
            batch_op.add_column(sa.Column("inode", sa.BigInteger(), nullable=True))
        if "mtime" not in track_cols:
            batch_op.add_column(sa.Column("mtime", sa.Float(), nullable=True))
        if "ix_tracks_inode" not in track_indexes:
            batch_op.create_index(batch_op.f("ix_tracks_inode"), ["inode"], unique=False)
        if "ix_tracks_normalized_title" not in track_indexes:
            batch_op.create_index(batch_op.f("ix_tracks_normalized_title"), ["normalized_title"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_normalized_title"))
        batch_op.drop_index(batch_op.f("ix_tracks_inode"))
        batch_op.drop_column("mtime")
        batch_op.drop_column("inode")
        batch_op.drop_column("normalized_title")

    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artists_normalized_name"))
        batch_op.drop_column("normalized_name")

    with op.batch_alter_table("albums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_albums_normalized_title"))
        batch_op.drop_column("normalized_title")

    # ### end Alembic commands ###
