"""add_normalized_hash_columns

Revision ID: eaf4b5d2df68
Revises: aac3c628374f
Create Date: 2026-06-17 07:06:44.430302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf4b5d2df68'
down_revision: Union[str, None] = 'aac3c628374f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_title', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_albums_normalized_title'), ['normalized_title'], unique=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_artists_normalized_name'), ['normalized_name'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('inode', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('mtime', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_inode'), ['inode'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_normalized_title'), ['normalized_title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_tracks_inode'))
        batch_op.drop_column('mtime')
        batch_op.drop_column('inode')
        batch_op.drop_column('normalized_title')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_normalized_name'))
        batch_op.drop_column('normalized_name')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_normalized_title'))
        batch_op.drop_column('normalized_title')

    # ### end Alembic commands ###
