"""v2.5.0_baseline_config

Revision ID: dccb620740d1
Revises:
Create Date: 2026-05-04 22:36:35.094387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dccb620740d1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "services" not in tables:
        op.create_table(
            "services",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("name", sa.TEXT(), nullable=False),
            sa.Column("namespace", sa.TEXT(), nullable=False),
            sa.Column("plugin_id", sa.INTEGER(), nullable=True),
            sa.Column("display_name", sa.TEXT(), nullable=True),
            sa.Column("service_type", sa.TEXT(), nullable=True),
            sa.Column("description", sa.TEXT(), nullable=True),
            sa.Column("is_active", sa.BOOLEAN(), server_default="1", nullable=False),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
        with op.batch_alter_table("services", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_services_name"), ["name"], unique=False
            )
    else:
        # Check for missing columns in existing table
        columns = [c["name"] for c in inspector.get_columns("services")]
        if "namespace" not in columns:
            op.add_column(
                "services",
                sa.Column(
                    "namespace", sa.TEXT(), nullable=False, server_default="legacy"
                ),
            )
        if "plugin_id" not in columns:
            op.add_column(
                "services", sa.Column("plugin_id", sa.INTEGER(), nullable=True)
            )
        if "is_active" not in columns:
            op.add_column(
                "services",
                sa.Column(
                    "is_active", sa.BOOLEAN(), server_default="1", nullable=False
                ),
            )

    if "service_config" not in tables:
        op.create_table(
            "service_config",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("service_id", sa.INTEGER(), nullable=False),
            sa.Column("config_key", sa.TEXT(), nullable=False),
            sa.Column("config_value", sa.TEXT(), nullable=True),
            sa.Column(
                "is_sensitive", sa.INTEGER(), server_default=sa.text("0"), nullable=True
            ),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["service_id"], ["services.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("service_id", "config_key"),
        )

    if "accounts" not in tables:
        op.create_table(
            "accounts",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("service_id", sa.INTEGER(), nullable=False),
            sa.Column("account_name", sa.TEXT(), nullable=True),
            sa.Column("display_name", sa.TEXT(), nullable=True),
            sa.Column("user_id", sa.TEXT(), nullable=True),
            sa.Column("account_email", sa.TEXT(), nullable=True),
            sa.Column(
                "is_active", sa.INTEGER(), server_default=sa.text("0"), nullable=True
            ),
            sa.Column(
                "is_authenticated",
                sa.INTEGER(),
                server_default=sa.text("0"),
                nullable=True,
            ),
            sa.Column("last_authenticated_at", sa.INTEGER(), nullable=True),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["service_id"], ["services.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("accounts", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_accounts_service"), ["service_id"], unique=False
            )

    if "account_tokens" not in tables:
        op.create_table(
            "account_tokens",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("account_id", sa.INTEGER(), nullable=False),
            sa.Column("access_token", sa.TEXT(), nullable=False),
            sa.Column("refresh_token", sa.TEXT(), nullable=True),
            sa.Column(
                "token_type",
                sa.TEXT(),
                server_default=sa.text("'Bearer'"),
                nullable=True,
            ),
            sa.Column("expires_at", sa.INTEGER(), nullable=True),
            sa.Column("scope", sa.TEXT(), nullable=True),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["account_id"], ["accounts.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("account_id"),
        )
        with op.batch_alter_table("account_tokens", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_tokens_account"), ["account_id"], unique=False
            )

    if "account_metadata" not in tables:
        op.create_table(
            "account_metadata",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("account_id", sa.INTEGER(), nullable=False),
            sa.Column("metadata_key", sa.TEXT(), nullable=False),
            sa.Column("metadata_value", sa.TEXT(), nullable=True),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["account_id"], ["accounts.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("account_id", "metadata_key"),
        )

    if "pkce_sessions" not in tables:
        op.create_table(
            "pkce_sessions",
            sa.Column("pkce_id", sa.TEXT(), nullable=False),
            sa.Column("service", sa.TEXT(), nullable=False),
            sa.Column("account_id", sa.INTEGER(), nullable=False),
            sa.Column("code_verifier", sa.TEXT(), nullable=False),
            sa.Column("code_challenge", sa.TEXT(), nullable=False),
            sa.Column("redirect_uri", sa.TEXT(), nullable=False),
            sa.Column("client_id", sa.TEXT(), nullable=False),
            sa.Column("created_at", sa.INTEGER(), nullable=False),
            sa.Column("expires_at", sa.INTEGER(), nullable=False),
            sa.ForeignKeyConstraint(
                ["account_id"], ["accounts.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("pkce_id"),
        )
        with op.batch_alter_table("pkce_sessions", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_pkce_expires"), ["expires_at"], unique=False
            )

    if "account_mappings" not in tables:
        op.create_table(
            "account_mappings",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("source_account_id", sa.INTEGER(), nullable=False),
            sa.Column("mapped_account_id", sa.INTEGER(), nullable=False),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.Column(
                "updated_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["mapped_account_id"], ["accounts.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(
                ["source_account_id"], ["accounts.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("source_account_id", "mapped_account_id"),
        )
        with op.batch_alter_table("account_mappings", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_account_mappings_source"),
                ["source_account_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("idx_account_mappings_mapped"),
                ["mapped_account_id"],
                unique=False,
            )

    if "plugin_snapshots" not in tables:
        op.create_table(
            "plugin_snapshots",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("namespace", sa.TEXT(), nullable=False),
            sa.Column("snapshot_data", sa.TEXT(), nullable=False),
            sa.Column("expires_at", sa.INTEGER(), nullable=False),
            sa.Column(
                "created_at",
                sa.INTEGER(),
                server_default=sa.text("(strftime('%s','now'))"),
                nullable=True,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("namespace"),
        )
        with op.batch_alter_table("plugin_snapshots", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_plugin_snapshots_ns"), ["namespace"], unique=False
            )
            batch_op.create_index(
                batch_op.f("idx_plugin_snapshots_expires"), ["expires_at"], unique=False
            )

    if "system_settings" not in tables:
        op.create_table(
            "system_settings",
            sa.Column("key", sa.String(), nullable=False),
            sa.Column("value", sa.Text(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("key"),
        )

    if "quality_profiles" not in tables:
        op.create_table(
            "quality_profiles",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("name", sa.String(), nullable=True),
            sa.Column("prefer_max_quality", sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if "quality_profile_steps" not in tables:
        op.create_table(
            "quality_profile_steps",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("profile_id", sa.String(), nullable=False),
            sa.Column("priority", sa.Integer(), nullable=False),
            sa.Column("rules", sa.JSON(), nullable=True),
            sa.ForeignKeyConstraint(
                ["profile_id"], ["quality_profiles.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_snapshots")
    op.drop_table("account_mappings")
    op.drop_table("pkce_sessions")
    op.drop_table("account_metadata")
    op.drop_table("account_tokens")
    op.drop_table("accounts")
    op.drop_table("service_config")
    op.drop_table("services")
    # ### end Alembic commands ###
