"""Merge User into Account and update UserTrackState

Revision ID: 22ff0c33fcfc
Revises: fedcba654323
Create Date: 2026-06-28 09:52:58.513727

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

import time_utils

# revision identifiers, used by Alembic.
revision: str = "22ff0c33fcfc"
down_revision: str | None = "fedcba654323"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plugin_id", sa.Integer(), nullable=False),
        sa.Column("remote_account_id", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plugin_id", "remote_account_id", name="uq_account_plugin_remote"
        ),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_plugin_id"), ["plugin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_accounts_remote_account_id"),
            ["remote_account_id"],
            unique=False,
        )

    op.create_table(
        "download_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_id", sa.String(), nullable=False),
        sa.Column("echo_sync_track", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", time_utils.UTCDateTime(), nullable=False),
        sa.Column("updated_at", time_utils.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("download_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_download_queue_provider_id"), ["provider_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_download_queue_sync_id"), ["sync_id"], unique=False
        )

    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_id", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("retry_count", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("last_checked_at", time_utils.UTCDateTime(), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_review_tasks_file_path"))
        batch_op.create_index(
            batch_op.f("ix_review_tasks_media_id"), ["media_id"], unique=False
        )
        batch_op.drop_column("file_path")

    with op.batch_alter_table("suggestion_staging_queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_suggestion_staging_queue_music_db_track_id"))
        batch_op.drop_index(batch_op.f("ix_suggestion_staging_queue_user_id"))
        batch_op.drop_constraint(
            batch_op.f("uq_suggestion_per_user_sync_reason"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_suggestion_per_user_track_reason"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_suggestion_staging_queue_account_id"),
            ["account_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_suggestion_per_account_sync_reason", ["account_id", "sync_id", "reason"]
        )
        batch_op.create_foreign_key(
            "fk_suggestion_staging_queue_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("music_db_track_id")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("user_album_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_user_album_ratings_user_id"))
        batch_op.drop_constraint(batch_op.f("uq_user_album_rating"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_user_album_rating", ["account_id", "album_urn"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_album_ratings_account_id"), ["account_id"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("fk_user_album_ratings_user_id_users"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_album_ratings_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("user_artist_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_user_artist_ratings_user_id"))
        batch_op.drop_constraint(batch_op.f("uq_user_artist_rating"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_user_artist_rating", ["account_id", "artist_urn"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_artist_ratings_account_id"),
            ["account_id"],
            unique=False,
        )
        batch_op.drop_constraint(
            batch_op.f("fk_user_artist_ratings_user_id_users"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_artist_ratings_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("user_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_user_ratings_user_id"))
        batch_op.drop_constraint(batch_op.f("uq_user_sync_id"), type_="unique")
        batch_op.create_unique_constraint("uq_user_sync_id", ["account_id", "sync_id"])
        batch_op.create_index(
            batch_op.f("ix_user_ratings_account_id"), ["account_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_user_ratings_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("user_track_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_user_track_states_user_id"))
        batch_op.drop_constraint(batch_op.f("uq_user_track_state"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_user_track_state", ["account_id", "sync_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_track_states_account_id"), ["account_id"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("fk_user_track_states_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_user_track_states_sponsor_id_users"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_track_states_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_user_track_states_sponsor_id_accounts",
            "accounts",
            ["sponsor_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.drop_column("user_id")

    op.drop_table("media_server_playlists")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("media_server_playlist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_server_playlist_items_playlist_id"))
        batch_op.drop_index(batch_op.f("ix_media_server_playlist_items_plugin_item_id"))

    op.drop_table("media_server_playlist_items")
    with op.batch_alter_table("downloads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_downloads_provider_id"))
        batch_op.drop_index(batch_op.f("ix_downloads_sync_id"))

    op.drop_table("downloads")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_track_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_user_track_states_sponsor_id_users"),
            "users",
            ["sponsor_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_track_states_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_user_track_states_account_id"))
        batch_op.drop_constraint("uq_user_track_state", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_track_state"), ["user_id", "sync_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_track_states_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("account_id")

    with op.batch_alter_table("user_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_user_ratings_account_id"))
        batch_op.drop_constraint("uq_user_sync_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_sync_id"), ["user_id", "sync_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_ratings_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("account_id")

    with op.batch_alter_table("user_artist_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_user_artist_ratings_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_user_artist_ratings_account_id"))
        batch_op.drop_constraint("uq_user_artist_rating", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_artist_rating"), ["user_id", "artist_urn"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_artist_ratings_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("account_id")

    with op.batch_alter_table("user_album_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_user_album_ratings_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_user_album_ratings_account_id"))
        batch_op.drop_constraint("uq_user_album_rating", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_album_rating"), ["user_id", "album_urn"]
        )
        batch_op.create_index(
            batch_op.f("ix_user_album_ratings_user_id"), ["user_id"], unique=False
        )
        batch_op.drop_column("account_id")

    with op.batch_alter_table("suggestion_staging_queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("music_db_track_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(
            "uq_suggestion_per_account_sync_reason", type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_suggestion_staging_queue_account_id"))
        batch_op.create_unique_constraint(
            batch_op.f("uq_suggestion_per_user_track_reason"),
            ["user_id", "music_db_track_id", "reason"],
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_suggestion_per_user_sync_reason"),
            ["user_id", "sync_id", "reason"],
        )
        batch_op.create_index(
            batch_op.f("ix_suggestion_staging_queue_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_suggestion_staging_queue_music_db_track_id"),
            ["music_db_track_id"],
            unique=False,
        )
        batch_op.drop_column("account_id")

    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_path", sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_review_tasks_media_id"))
        batch_op.create_index(
            batch_op.f("ix_review_tasks_file_path"), ["file_path"], unique=1
        )
        batch_op.drop_column("last_checked_at")
        batch_op.drop_column("retry_count")
        batch_op.drop_column("media_id")

    op.create_table(
        "downloads",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("sync_id", sa.VARCHAR(), nullable=False),
        sa.Column("echo_sync_track", sqlite.JSON(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("provider_id", sa.VARCHAR(), nullable=True),
        sa.Column("retry_count", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downloads")),
    )
    with op.batch_alter_table("downloads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_downloads_sync_id"), ["sync_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_downloads_provider_id"), ["provider_id"], unique=False
        )

    op.create_table(
        "media_server_playlist_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("playlist_id", sa.INTEGER(), nullable=False),
        sa.Column("plugin_item_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["media_server_playlists.id"],
            name=op.f(
                "fk_media_server_playlist_items_playlist_id_media_server_playlists"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_server_playlist_items")),
        sa.UniqueConstraint(
            "playlist_id", "plugin_item_id", name=op.f("uq_playlist_item")
        ),
    )
    with op.batch_alter_table("media_server_playlist_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_server_playlist_items_plugin_item_id"),
            ["plugin_item_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_media_server_playlist_items_playlist_id"),
            ["playlist_id"],
            unique=False,
        )

    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("provider_identifier", sa.VARCHAR(), nullable=True),
        sa.Column("provider", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "provider_identifier", name=op.f("uq_users_provider_identifier")
        ),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=1)

    op.create_table(
        "media_server_playlists",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("server_source", sa.VARCHAR(), nullable=False),
        sa.Column("playlist_id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_server_playlists")),
        sa.UniqueConstraint(
            "server_source", "playlist_id", name=op.f("uq_media_server_playlist")
        ),
    )
    with op.batch_alter_table("download_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_download_queue_sync_id"))
        batch_op.drop_index(batch_op.f("ix_download_queue_provider_id"))

    op.drop_table("download_queue")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_remote_account_id"))
        batch_op.drop_index(batch_op.f("ix_accounts_plugin_id"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
