"""v2.3.0 Baseline Schema — working.db

This revision captures the exact working.db schema that shipped with v2.3.0.
It is used as the stamp target by the Smart Inspector in run_auto_migrations()
when adopting a legacy (pre-Alembic) database so that only the v2.4.0
additions (revision a1b2c3d4e5f6) are applied on first migration.

Revision ID: 4661df33cf8b
Revises:
Create Date: 2026-03-28 05:36:47.525189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import time_utils


# revision identifiers, used by Alembic.
revision: str = '4661df33cf8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(), nullable=False),
    sa.Column('echo_sync_track', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', time_utils.UTCDateTime(), nullable=False),
    sa.Column('updated_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_sync_id'), ['sync_id'], unique=False)

    op.create_table('media_server_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_source', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_source', 'playlist_id', name='uq_media_server_playlist')
    )
    op.create_table('playback_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider_item_id', sa.String(), nullable=False),
    sa.Column('listened_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_item_id', 'listened_at', name='uq_playback_history')
    )
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playback_history_listened_at'), ['listened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_history_provider_item_id'), ['provider_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_history_user_id'), ['user_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_metadata', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_file_path'), ['file_path'], unique=True)

    op.create_table('suggestion_staging_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('music_db_track_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('ui_label', sa.String(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', time_utils.UTCDateTime(), nullable=False),
    sa.Column('updated_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'music_db_track_id', 'reason', name='uq_suggestion_per_user_track_reason'),
    sa.UniqueConstraint('user_id', 'sync_id', 'reason', name='uq_suggestion_per_user_sync_reason')
    )
    with op.batch_alter_table('suggestion_staging_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_staging_queue_music_db_track_id'), ['music_db_track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_staging_queue_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_staging_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_staging_queue_sync_id'), ['sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_staging_queue_user_id'), ['user_id'], unique=False)

    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sync_id', name='uq_user_sync_id')
    )
    with op.batch_alter_table('user_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ratings_sync_id'), ['sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('provider_identifier', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_identifier')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('watchlist_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('last_scan_timestamp', time_utils.UTCDateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', time_utils.UTCDateTime(), nullable=False),
    sa.Column('updated_at', time_utils.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_artists_spotify_artist_id'), ['spotify_artist_id'], unique=True)

    op.create_table('media_server_playlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('provider_item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['media_server_playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'provider_item_id', name='uq_playlist_item')
    )
    with op.batch_alter_table('media_server_playlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_server_playlist_items_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_server_playlist_items_provider_item_id'), ['provider_item_id'], unique=False)

    op.create_table('user_album_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_urn', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'album_urn', name='uq_user_album_rating')
    )
    with op.batch_alter_table('user_album_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_album_ratings_album_urn'), ['album_urn'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_album_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('user_artist_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_urn', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist_urn', name='uq_user_artist_rating')
    )
    with op.batch_alter_table('user_artist_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_artist_ratings_artist_urn'), ['artist_urn'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_artist_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('user_track_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(), nullable=False),
    sa.Column('is_unlinked', sa.Boolean(), nullable=False),
    sa.Column('is_hard_deleted', sa.Boolean(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('admin_exempt_deletion', sa.Boolean(), nullable=False),
    sa.Column('admin_force_upgrade', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_action', sa.String(), nullable=True),
    sa.Column('lifecycle_queued_at', time_utils.UTCDateTime(), nullable=True),
    sa.Column('updated_at', time_utils.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sync_id', name='uq_user_track_state')
    )
    with op.batch_alter_table('user_track_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_track_states_lifecycle_action'), ['lifecycle_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_track_states_sponsor_id'), ['sponsor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_track_states_sync_id'), ['sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_track_states_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_track_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_track_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_track_states_sync_id'))
        batch_op.drop_index(batch_op.f('ix_user_track_states_sponsor_id'))
        batch_op.drop_index(batch_op.f('ix_user_track_states_lifecycle_action'))

    op.drop_table('user_track_states')
    with op.batch_alter_table('user_artist_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_artist_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_artist_ratings_artist_urn'))

    op.drop_table('user_artist_ratings')
    with op.batch_alter_table('user_album_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_album_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_album_ratings_album_urn'))

    op.drop_table('user_album_ratings')
    with op.batch_alter_table('media_server_playlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_server_playlist_items_provider_item_id'))
        batch_op.drop_index(batch_op.f('ix_media_server_playlist_items_playlist_id'))

    op.drop_table('media_server_playlist_items')
    with op.batch_alter_table('watchlist_artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_artists_spotify_artist_id'))

    op.drop_table('watchlist_artists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('user_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_ratings_sync_id'))

    op.drop_table('user_ratings')
    with op.batch_alter_table('suggestion_staging_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_staging_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_staging_queue_sync_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_staging_queue_status'))
        batch_op.drop_index(batch_op.f('ix_suggestion_staging_queue_reason'))
        batch_op.drop_index(batch_op.f('ix_suggestion_staging_queue_music_db_track_id'))

    op.drop_table('suggestion_staging_queue')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_file_path'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playback_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_playback_history_provider_item_id'))
        batch_op.drop_index(batch_op.f('ix_playback_history_listened_at'))

    op.drop_table('playback_history')
    op.drop_table('media_server_playlists')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_sync_id'))
        batch_op.drop_index(batch_op.f('ix_downloads_provider_id'))

    op.drop_table('downloads')
    # ### end Alembic commands ###
