"""add_virtual_track_cache

Revision ID: ba366761575f
Revises: fedcba654324
Create Date: 2026-07-29 07:11:53.299014

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import time_utils

# revision identifiers, used by Alembic.
revision: str = "ba366761575f"
down_revision: str | None = "fedcba654324"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "virtual_track_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist_name", sa.String(), nullable=False),
        sa.Column("album_title", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("isrc", sa.String(), nullable=True),
        sa.Column("external_uri", sa.String(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", time_utils.UTCDateTime(), nullable=False),
        sa.Column("updated_at", time_utils.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("virtual_track_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_album_title"),
            ["album_title"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_artist_name"),
            ["artist_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_external_uri"),
            ["external_uri"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_isrc"), ["isrc"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_provider_id"),
            ["provider_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_track_cache_title"), ["title"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("virtual_track_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_title"))
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_provider_id"))
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_isrc"))
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_external_uri"))
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_artist_name"))
        batch_op.drop_index(batch_op.f("ix_virtual_track_cache_album_title"))

    op.drop_table("virtual_track_cache")
    # ### end Alembic commands ###
